version: '3.2'

services:
  db:
    image: mysql/mysql-server:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=0
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=sites_html
      - MYSQL_USER=joomla
      - MYSQL_PASSWORD=joomla
    command: ["mysqld", "--sql-mode=ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"]
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  demo:
    depends_on:
      - db
    build: .
    ports:
      - "8081:8081"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=joomla
      - MYSQL_PWD=joomla
      - MYSQL_DB=sites_testing
      - ENVIRONMENT=local
      - PHP_OPCACHE_ENABLE=off
      - PHP_DISPLAY_ERRORS=on
      - PHP_ERROR_REPORTING=30719
    volumes:
      - ./html/:/var/www/html:cached