version: '3.2'

services:
  plainnginx:
    image: plain/nginx:local
    ports:
      - "8081:8081"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=joomla
      - MYSQL_PWD=joomla
      - MYSQL_DB=sites_testing
      - ENVIRONMENT=local
      - PHP_OPCACHE_ENABLE=off
      - PHP_DISPLAY_ERRORS=on
      - PHP_ERROR_REPORTING=30719