name: CI
on:
  push:
    branches:
      - master
      - feature/*

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Remove previous images
        run: docker-compose rm -f
      - name: build base image
        run: docker build --no-cache -t actions/codeception:local .
      - name: Compose
        run: docker-compose up  --build -d
      - name: Get environment details
        run: printenv
      - name: List docker containers
        run: docker container ps
      - name: Sleep, wait for db
        run: sleep 5
      - name: Set up site
        run: docker-compose run demo "/usr/local/bin/bootstrap.sh"
      - name: Curl site
        run: curl -X GET http://localhost:8081
      #- name: List directory
