name: CI
on:
  push:
    branches:
      - master
      - feature/*

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run: docker-compose -f ${{ github.repository }}/docker-compose.yml  up --exit-code-from

      - name: Set up site
        run: docker-compose -f ${{ github.repository }}/docker-compose.yml exec demo /bin/sh -c "/usr/local/bin/bootstrap.sh"

      - name: Curl site
        run curl -X GET http://localhost:8001